/********************************************************************
* SelDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SelDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSelDict();
extern void G__cpp_setup_inheritanceSelDict();
extern void G__cpp_setup_typetableSelDict();
extern void G__cpp_setup_memvarSelDict();
extern void G__cpp_setup_globalSelDict();
extern void G__cpp_setup_memfuncSelDict();
extern void G__cpp_setup_funcSelDict();
extern void G__set_cpp_environmentSelDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "AllPix_Hits_WriteToEntuple.h"
#include "AllPix_Frames_WriteToEntuple.h"
#include "allpix_dm.h"
#include "AllPixDigitAnimation.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SelDictLN_TClass;
extern G__linked_taginfo G__SelDictLN_TBuffer;
extern G__linked_taginfo G__SelDictLN_TMemberInspector;
extern G__linked_taginfo G__SelDictLN_TObject;
extern G__linked_taginfo G__SelDictLN_TString;
extern G__linked_taginfo G__SelDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__SelDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__SelDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SelDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SelDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SelDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SelDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SelDictLN_TFile;
extern G__linked_taginfo G__SelDictLN_TTree;
extern G__linked_taginfo G__SelDictLN_TBranch;
extern G__linked_taginfo G__SelDictLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__SelDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR;
extern G__linked_taginfo G__SelDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__SelDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__SelDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__SelDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__SelDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__SelDictLN_TH2;
extern G__linked_taginfo G__SelDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__SelDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__SelDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__SelDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__SelDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__SelDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__SelDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__SelDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__SelDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__SelDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__SelDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__SelDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__SelDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__SelDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__SelDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__SelDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__SelDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__SelDictLN_SimpleHits;
extern G__linked_taginfo G__SelDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__SelDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SelDictLN_vectorlETVector3cOallocatorlETVector3gRsPgR;
extern G__linked_taginfo G__SelDictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SelDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__SelDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SelDictLN_FramesHandler;
extern G__linked_taginfo G__SelDictLN_FrameStruct;
extern G__linked_taginfo G__SelDictLN_WriteToNtuple;
extern G__linked_taginfo G__SelDictLN_FrameContainer;
extern G__linked_taginfo G__SelDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR;
extern G__linked_taginfo G__SelDictLN_TGeoMedium;
extern G__linked_taginfo G__SelDictLN_TGeoBBox;
extern G__linked_taginfo G__SelDictLN_TGeoVolume;
extern G__linked_taginfo G__SelDictLN_TGeoManager;
extern G__linked_taginfo G__SelDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR;
extern G__linked_taginfo G__SelDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SelDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR;
extern G__linked_taginfo G__SelDictLN_AllPixDigitAnimation;

/* STUB derived class for protected member access */
